# Authors: Code generated by Google Gemini and comments done by Daniel Holgate
# Date: 16/09/2025
# Description: Code for taking the raw output of the event descriptions generated and formats the properly generated 
# description-event pairs

# Input file must be changed to whatever your raw output file was from ExplainEvent.py and the output file can be
# whatever you want to name it.
INPUT_FILE = ""
OUTPUT_FILE = ""

# Method for extracting the description-event pairs into a list.
def extract_event_description_pairs(filename):
    pairs = []
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    for i in range(len(lines) - 1):
        line = lines[i].strip()
        next_line = lines[i+1].strip()
        
        # Looks for each properly formatted description-event pair, Event: followed on the next line by Description:. This is to
        # ensure both an event and a description are present and not missing as both are necessary to have.
        if line.startswith("Event:") and next_line.startswith("Description:"):
            event = line[len("Event:"):].strip()
            event = event.lower()
            event = event.replace(" ", "_")
            description = next_line[len("Description:"):].strip()
            
            if event and description:
                pairs.append({"Event": event, "Description": description})
    return pairs

pairs = extract_event_description_pairs(INPUT_FILE)
for pair in pairs:
    with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
        f.write(f"\"{pair['Event']}\": \"{pair['Description']}\"\n")