# Authors: Code generated by ChatGPT online and comments done by Daniel Holgate
# Date: 16/09/2025
# Description: Code for selecting a small subset of the total generated outlines from GenOutlines.py to create initial 
# paragraphs for later.

import random

# Input file must be changed to whatever your generated outlines file from GenOutlines.py was and the output file can be
# whatever you want to name it.
INPUT_FILE = ""
OUTPUT_FILE = ""

# Method for selecting a random selection of outlines of the specified amount.
def select_random_outlines(input_file, output_file, num_to_select=250):
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            outlines = [line.strip() for line in f if line.strip()]

        # If are asking for more outlines than was generated, will just use all those available.
        if len(outlines) < num_to_select:
            print(f"Warning: Only {len(outlines)} outlines available, selecting all of them.")
            selected = outlines
        else:
            # Extracts the number of outlines at random from the total outlines.
            selected = random.sample(outlines, num_to_select)

        with open(output_file, 'w', encoding='utf-8') as f:
            for outline in selected:
                f.write(outline + '\n')

        print(f"{len(selected)} outlines written to '{output_file}'.")

    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found.")
    except Exception as e:
        print(f"Unexpected error: {e}")

select_random_outlines(INPUT_FILE, OUTPUT_FILE)
