#!/bin/sh
#
# This is a sample Slurm batch script for running Python scripts sequentially on the UCT HPC.
# It requests resources and then executes the Python scripts one after another.

# Slurm Directives:
# These lines start with #SBATCH and tell the Slurm scheduler about your job requirements.

# Account to charge for this job.
#SBATCH --account=compsci

# Specify the partition (queue) to submit your job to.
# Based on your example, 'ada' is used.
#SBATCH --partition=ada

# Request 1 node.
#SBATCH --nodes=1

# Request 1 task (process). This is suitable for single-threaded Python scripts.
#SBATCH --ntasks=1

# Set the maximum time your job will run (e.g., 2 hours).
# Adjust this if the combined runtime of all scripts exceeds this.
#SBATCH --time=3:00:00

# Job name: This will appear in the squeue output.
#SBATCH --job-name="LLaMA-Extraction-And-Outline-Gen"

# Output file for standard output (stdout)
# %j will be replaced by the job ID.
#SBATCH --output=LLaMA-Extraction-And-Outline-Gen_%j.out

# Error file for standard error (stderr)
# %j will be replaced by the job ID.
#SBATCH --error=LLaMA-Extraction-And-Outline-Gen_%j.err

# --- End of Slurm Directives ---

# Load the specified Python module.
# This uses the miniconda3-py3.12 environment.
module load python/miniconda3-py3.12

# --- Execute Python Scripts Sequentially ---

# Run the first Python script. It will generate 'themes_data.json'.
echo "Starting Themes.py..."
python Themes.py
# Check if Themes.py ran successfully (optional but good practice)
if [ $? -ne 0 ]; then
    echo "Error: Themes.py failed. Exiting."
    exit 1
fi
echo "Themes.py finished."

echo "Starting ThemeFix.py..."
python ThemeFix.py
if [ $? -ne 0 ]; then
    echo "Error: ThemeFix.py failed. Exiting."
    exit 1
fi
echo "ThemeFix.py finished."

# Run the second Python script. Its output file (if any) is independent for the next step.
echo "Starting Events.py..."
python Events.py
if [ $? -ne 0 ]; then
    echo "Error: Events.py failed. Exiting."
    exit 1
fi
echo "Events.py finished."

# Run the third Python script. It will read 'themes_data.json' generated by Themes.py.
# Replace 'YourThirdPythonScript.py' with the actual name of your third Python file.
echo "Starting ExplainEvent.py..."
python ExplainEvent.py
if [ $? -ne 0 ]; then
    echo "Error: ExplainEvent.py failed. Exiting."
    exit 1
fi
echo "ExplainEvent.py finished."

echo "Starting DescriptionConvert.py..."
python DescriptionConvert.py
if [ $? -ne 0 ]; then
    echo "Error: DescriptionConvert.py failed. Exiting."
    exit 1
fi
echo "DescriptionConvert.py finished."

echo "Starting ParaTransition.py..."
python ParaTransition.py
if [ $? -ne 0 ]; then
    echo "Error: ParaTransition.py failed. Exiting."
    exit 1
fi
echo "ParaTransition.py finished."

echo "Starting GenerateLpFunction.py..."
python GenerateLpFunction.py
if [ $? -ne 0 ]; then
    echo "Error: GenerateLpFunction.py failed. Exiting."
    exit 1
fi
echo "GenerateLpFunction.py finished."

echo "Starting GenOutlines.py..."
python GenOutlines.py
# Check if Themes.py ran successfully (optional but good practice)
if [ $? -ne 0 ]; then
    echo "Error: GenOutlines.py failed. Exiting."
    exit 1
fi
echo "GenOutlines.py finished."

echo "Starting ExtractOutlines.py..."
python extract_outlines.py
# Check if Themes.py ran successfully (optional but good practice)
if [ $? -ne 0 ]; then
    echo "Error: ExtractOutlines.py failed. Exiting."
    exit 1
fi
echo "ExtractOutlines.py finished."

echo "All Python scripts finished."

echo "All Python scripts finished."