# Author: Code generated by ChatGPT online, comments by Daniel Holgate
# Date: 07/08/2025
# Description: code for preprocessing the Aesop for Children with each story being output as a single paragraph with
# no extra information
import re

# Method for preprocessing each story into a single paragraph
def extract_story_text(block):
    
    # Takes out the trailing whitespace, triple quotes and commas around the story
    block = block.strip().strip('""",').strip()

    # Takes all the non-empty lines in block and places them in an array
    lines = [line.strip() for line in block.splitlines() if line.strip()]

    if len(lines) < 3:
        return None  # Skip malformed blocks

    # Extracts just the lines of story text to remove title and dataset name
    content_lines = lines[2:]

    # Combines the story text into a single paragraph
    story = ' '.join(content_lines)
    story = re.sub(r'\s+', ' ', story.strip())  # Normalize whitespace

    return story

# Reads in Aesop for Children dataset
with open("AFP.txt", "r", encoding="utf-8") as infile:
    content = infile.read()

# Places each story block in an array
story_blocks = re.findall(r'""".*?"""[,]*', content, re.DOTALL)

# Processes all the stories, skipping over empty ones
cleaned_stories = [extract_story_text(block) for block in story_blocks if extract_story_text(block)]

# Outputs the single paragraph stories, separated by a single empty line
with open("AFP_cleaned_stories.txt", "w", encoding="utf-8") as outfile:
    for story in cleaned_stories:
        outfile.write(story + "\n\n")
